# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import file.compute_pb2 as compute__pb2


class ComputeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/compute.Compute/SayHello',
                request_serializer=compute__pb2.HelloRequest.SerializeToString,
                response_deserializer=compute__pb2.HelloReply.FromString,
                )
        self.skeleton_calculate = channel.unary_unary(
                '/compute.Compute/skeleton_calculate',
                request_serializer=compute__pb2.skeletonRequest.SerializeToString,
                response_deserializer=compute__pb2.skeletonReply.FromString,
                )


class ComputeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def skeleton_calculate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComputeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=compute__pb2.HelloRequest.FromString,
                    response_serializer=compute__pb2.HelloReply.SerializeToString,
            ),
            'skeleton_calculate': grpc.unary_unary_rpc_method_handler(
                    servicer.skeleton_calculate,
                    request_deserializer=compute__pb2.skeletonRequest.FromString,
                    response_serializer=compute__pb2.skeletonReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'compute.Compute', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Compute(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/compute.Compute/SayHello',
            compute__pb2.HelloRequest.SerializeToString,
            compute__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def skeleton_calculate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/compute.Compute/skeleton_calculate',
            compute__pb2.skeletonRequest.SerializeToString,
            compute__pb2.skeletonReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
