# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compute.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcompute.proto\x12\x07\x63ompute\"\"\n\x0cHelloRequest\x12\x12\n\nhelloworld\x18\x01 \x01(\t\"\x1c\n\nHelloReply\x12\x0e\n\x06result\x18\x01 \x01(\t\"8\n\x0fskeletonRequest\x12\x10\n\x08skeleton\x18\x01 \x01(\t\x12\x13\n\x0bskeleton_id\x18\x02 \x01(\t\"#\n\rskeletonReply\x12\x12\n\nmap_result\x18\x01 \x01(\t2\x8d\x01\n\x07\x43ompute\x12\x38\n\x08SayHello\x12\x15.compute.HelloRequest\x1a\x13.compute.HelloReply\"\x00\x12H\n\x12skeleton_calculate\x12\x18.compute.skeletonRequest\x1a\x16.compute.skeletonReply\"\x00\x62\x06proto3')



_HELLOREQUEST = DESCRIPTOR.message_types_by_name['HelloRequest']
_HELLOREPLY = DESCRIPTOR.message_types_by_name['HelloReply']
_SKELETONREQUEST = DESCRIPTOR.message_types_by_name['skeletonRequest']
_SKELETONREPLY = DESCRIPTOR.message_types_by_name['skeletonReply']
HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'compute_pb2'
  # @@protoc_insertion_point(class_scope:compute.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'compute_pb2'
  # @@protoc_insertion_point(class_scope:compute.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

skeletonRequest = _reflection.GeneratedProtocolMessageType('skeletonRequest', (_message.Message,), {
  'DESCRIPTOR' : _SKELETONREQUEST,
  '__module__' : 'compute_pb2'
  # @@protoc_insertion_point(class_scope:compute.skeletonRequest)
  })
_sym_db.RegisterMessage(skeletonRequest)

skeletonReply = _reflection.GeneratedProtocolMessageType('skeletonReply', (_message.Message,), {
  'DESCRIPTOR' : _SKELETONREPLY,
  '__module__' : 'compute_pb2'
  # @@protoc_insertion_point(class_scope:compute.skeletonReply)
  })
_sym_db.RegisterMessage(skeletonReply)

_COMPUTE = DESCRIPTOR.services_by_name['Compute']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=26
  _HELLOREQUEST._serialized_end=60
  _HELLOREPLY._serialized_start=62
  _HELLOREPLY._serialized_end=90
  _SKELETONREQUEST._serialized_start=92
  _SKELETONREQUEST._serialized_end=148
  _SKELETONREPLY._serialized_start=150
  _SKELETONREPLY._serialized_end=185
  _COMPUTE._serialized_start=188
  _COMPUTE._serialized_end=329
# @@protoc_insertion_point(module_scope)
